package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;
import java.util.Optional;
import java.util.function.Supplier;

import org.photonvision.targeting.PhotonTrackedTarget;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModule.SteerRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ForwardPerspectiveValue;
import com.ctre.phoenix6.swerve.SwerveRequest.SwerveDriveBrake;

import choreo.Choreo.TrajectoryLogger;
import choreo.auto.AutoFactory;
import choreo.trajectory.SwerveSample;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.vision.Detection;
import frc.util.WaltDriverStation;
import frc.util.WaltLogger;
import frc.util.WaltLogger.DoubleLogger;
import frc.util.WaltLogger.Pose2dLogger;

/*
 * Swerve
 *
 * This is our drivetrain subsystem. It extends TunerSwerveDrivetrain (generated
 * by CTRE Tuner X) and adds our own behavior on top of it.
 *
 * Quick primer on swerve drive (skip if you know it already):
 *   A swerve drivetrain has four independently steered + driven wheel modules.
 *   Each module can point in any direction, so the robot can strafe, spin, and
 *   drive at the same time. We use "field-centric" control so pushing "forward"
 *   on the joystick always moves toward the opposing alliance wall, regardless
 *   of which way the robot happens to be facing.
 *
 * What this class adds on top of the CTRE base:
 *   - Alliance-aware "operator perspective" so field-centric works correctly for
 *     both Red and Blue (they face opposite directions on the field).
 *   - Choreo path following: followPath() is called by Choreo each loop tick
 *     during auton to track a pre-planned trajectory.
 *   - Helper commands: xBrakeCmd, roboToPose, roboToRotation, etc.
 *   - Logging of chassis speeds and odometry data to AdvantageScope.
 *   - SysId support for characterizing the drive motors.
 *
 * The hardware config (module positions, gear ratios, PID gains, CAN IDs, etc.)
 * lives in TunerConstants, generated by Tuner X:
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class Swerve extends TunerSwerveDrivetrain implements Subsystem {

    // ---- simulation ----
    // The CTRE drivetrain sim needs to run faster than the main 20 ms robot loop
    // so its PID loops behave like they do on the real robot. A Notifier fires
    // the sim update at 4 ms on its own thread.
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    // Converts individual module states (speed + direction) to/from overall robot speed.
    // Used in periodic() to compute and log total chassis speed.
    public SwerveDriveKinematics m_kinematics = new SwerveDriveKinematics(getModuleLocations());

    private final StatusSignal<Angle> sig_gyroRoll = getPigeon2().getRoll();
    private final StatusSignal<Angle> sig_gyroYaw = getPigeon2().getYaw();

    // ---- alliance perspective ----
    // Field-centric drive uses a fixed field coordinate frame.
    // Blue alliance treats 0° as forward (toward the red wall).
    // Red alliance treats 180° as forward (toward the blue wall).
    // We update this in periodic() so it re-applies automatically if the robot
    // code restarts mid-match.
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    private boolean m_hasAppliedOperatorPerspective = false;

    // ---- path following PID controllers ----
    // During Choreo auton, these three controllers correct for the robot drifting
    // off the planned trajectory. Choreo provides feed-forward velocities from the
    // trajectory itself, and these PIDs add a correction term on top based on the
    // error between our actual pose and the desired pose.
    //   X/Y controllers  - correct position error in meters
    //   Theta controller - correct heading error in radians, with continuous input
    //                      so it wraps at ±π (takes the short way around)
    private final PIDController m_pathXController = new PIDController(4.69, 0, 0);
    private final PIDController m_pathYController = new PIDController(4.69, 0, 0);
    private final PIDController m_pathThetaController = new PIDController(4.68, 0, 0);

    // The swerve request that actually sends corrected speeds to the modules.
    // Velocity + Position request types give better tracking accuracy than open-loop.
    private final SwerveRequest.ApplyFieldSpeeds m_pathApplyFieldSpeeds = new SwerveRequest.ApplyFieldSpeeds()
        .withDriveRequestType(DriveRequestType.Velocity)
        .withSteerRequestType(SteerRequestType.Position);

    private final Detection detection = new Detection();

    // ---- loggers ----
    private final DoubleLogger log_absoluteRobotSpeed = new WaltLogger.DoubleLogger("Swerve", "absoluteRobotSpeed");
    private final DoubleLogger log_vxMPS = new DoubleLogger("Swerve", "vxMPS");
    private final DoubleLogger log_vyMPS = new DoubleLogger("Swerve", "vyMPS");
    private final Pose2dLogger log_sampleAt_pose = new Pose2dLogger("Swerve/Autons", "sampleAt_Pose");
    private final DoubleLogger log_currentAutonTotalTime = new DoubleLogger("Swerve/Auton", "currentTotalTime");
    private final DoubleLogger log_sampleAt_velocityX = new DoubleLogger("Swerve/Auton", "sampleAt_velocityX");
    private final DoubleLogger log_sampleAt_velocityY = new DoubleLogger("Swerve/Auton", "sampleAt_velocityY");

    // Field-centric drive request used by the pose-targeting helpers.
    // BlueAlliance perspective means "forward" = toward red wall for both alliances.
    private final SwerveRequest.FieldCentric swreq_drive = new SwerveRequest.FieldCentric()
        .withForwardPerspective(ForwardPerspectiveValue.BlueAlliance);

    // ---- SysId ----
    // SysId (System Identification) is a WPILib tool that characterizes the drive
    // motors by logging their response to known voltage inputs, then computing
    // feedforward and PID gains from the data. Only translation is currently active.
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
        new SwerveRequest.SysIdSwerveTranslation();

    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // default ramp rate (1 V/s)
            Volts.of(4), // 4 V step to avoid brownout
            null,        // default timeout (10 s)
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;


    // =============================================================
    // CONSTRUCTORS
    // (generated by CTRE Tuner X — the hardware config lives in TunerConstants)
    // =============================================================

    /** Standard constructor — uses default odometry update frequency. */
    public Swerve(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) startSimThread();
    }

    /** Constructor with a custom odometry update frequency. */
    public Swerve(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) startSimThread();
    }

    /**
     * Constructor with custom odometry frequency and separate standard deviations
     * for wheel odometry vs. vision pose estimates. The Kalman filter uses these
     * to decide how much to trust each source.
     */
    public Swerve(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) startSimThread();
    }


    // =============================================================
    // SYSID
    // =============================================================

    /** Runs the quasistatic (slow voltage ramp) SysId test. */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /** Runs the dynamic (step voltage) SysId test. */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }


    // =============================================================
    // CORE COMMANDS
    // =============================================================

    /**
     * Applies a swerve request every loop while the command runs.
     * Most driver commands use this pattern:
     *   applyRequest(() -> swreq_drive.withVelocityX(x).withVelocityY(y))
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Locks all four wheel modules into an X-pattern (each pointing 45° outward).
     * This creates a passive brake — the robot resists being pushed in any direction.
     * Used at the end of auton so the robot doesn't slide after stopping.
     */
    public Command xBrakeCmd() {
        final SwerveRequest.SwerveDriveBrake stopReq = new SwerveDriveBrake();
        return runOnce(() -> setControl(stopReq));
    }

    /** Returns the robot's current velocity as vx, vy, omega (ChassisSpeeds). */
    public ChassisSpeeds getChassisSpeeds() {
        return m_kinematics.toChassisSpeeds(getState().ModuleStates);
    }


    // =============================================================
    // VISION
    // =============================================================

    /**
     * Fuses a PhotonVision pose measurement into the Kalman filter odometry.
     * The FPGA timestamp conversion corrects for processing latency.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Same as above but also updates the vision standard deviations, which control
     * how much the filter trusts this measurement relative to wheel odometry.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Looks up the estimated robot pose at a past timestamp by interpolating the
     * odometry history buffer. Useful for matching vision detections to where the
     * robot was when the camera frame was actually captured.
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }


    // =============================================================
    // PATH FOLLOWING (CHOREO)
    // =============================================================

    // Called by Choreo every loop tick during auton.
    // The SwerveSample has the desired pose + chassis speeds at this trajectory timestamp.
    // We take Choreo's feed-forward velocities and add PID correction on top
    // to stay on the planned path even if the robot drifts slightly.
    private void followPath(SwerveSample sample) {
        m_pathThetaController.enableContinuousInput(-Math.PI, Math.PI); // wrap heading at ±π

        var pose = getState().Pose;
        var targetSpeeds = sample.getChassisSpeeds(); // feed-forward from Choreo

        // Add PID correction for each axis of error.
        targetSpeeds.vxMetersPerSecond += m_pathXController.calculate(pose.getX(), sample.x);
        targetSpeeds.vyMetersPerSecond += m_pathYController.calculate(pose.getY(), sample.y);
        targetSpeeds.omegaRadiansPerSecond += m_pathThetaController.calculate(
            pose.getRotation().getRadians(), sample.heading);

        // Apply to the swerve modules, including per-module force feedforwards from
        // Choreo for better tracking on aggressive paths.
        setControl(
            m_pathApplyFieldSpeeds.withSpeeds(targetSpeeds)
                .withWheelForceFeedforwardsX(sample.moduleForcesX())
                .withWheelForceFeedforwardsY(sample.moduleForcesY())
        );
    }

    /**
     * Creates the Choreo AutoFactory used by WaltAdaptableAutonFactory.
     * The trajectory logger fires at the start/end of each trajectory and
     * logs a sample at t=4.25 s for pre-match path verification.
     */
    public AutoFactory createAutoFactory() {
        return createAutoFactory((traj, isStart) -> {
            SwerveSample sample = traj.sampleAt(4.25, false).get();
            WaltLogger.timedPrint(String.format("TrajLog - isStart: %b", isStart));
            WaltLogger.timedPrint("Sample at 4.25s (PRE BUMP); X:" + sample.getPose().getX()
                + " Y:" + traj.sampleAt(4.25, false).get().getPose().getY());
            log_sampleAt_pose.accept(sample.getPose());
            log_sampleAt_velocityX.accept(sample.vx);
            log_sampleAt_velocityY.accept(sample.vy);
            log_currentAutonTotalTime.accept(traj.getTotalTime());
        });
    }

    /** Creates a Choreo AutoFactory with a custom trajectory logger. */
    public AutoFactory createAutoFactory(TrajectoryLogger<SwerveSample> trajLogger) {
        return new AutoFactory(
            () -> getState().Pose,
            this::resetPose,
            this::followPath,
            true, // auto-flip trajectories for red alliance
            this,
            trajLogger
        );
    }


    // =============================================================
    // POSE-TARGETING HELPERS
    // =============================================================
    // Simple PID-based "go to this pose" commands used outside of Choreo auton
    // (e.g. auto-alignment, short position corrections). Not as smooth as a
    // full Choreo path but useful for quick corrections.

    /**
     * Drives the robot to a target Pose2d using the path PID controllers.
     * Stops once within `tolerance` meters of the target translation.
     */
    public Command roboToPose(Pose2d desPose, double tolerance) {
        return Commands.runOnce(() -> {
            Pose2d curPose = getState().Pose;
            double xSpeed = m_pathXController.calculate(curPose.getX(), desPose.getX());
            double ySpeed = m_pathYController.calculate(curPose.getY(), desPose.getY());
            double thetaSpeed = m_pathThetaController.calculate(
                curPose.getRotation().getRadians(), desPose.getRotation().getRadians());
            setControl(swreq_drive.withVelocityX(xSpeed).withVelocityY(ySpeed).withRotationalRate(thetaSpeed));
        }).andThen(Commands.waitUntil(() -> isNearPose(getState().Pose, desPose, tolerance)))
          .andThen(() -> setControl(swreq_drive.withVelocityX(0).withVelocityY(0).withRotationalRate(0)));
    }

    /** Rotates to a target heading only (no translation). Stops within `tolerance` radians. */
    public Command roboToRotation(Rotation2d desRotation, double tolerance) {
        return Commands.runOnce(() -> {
            Rotation2d curRotation = getState().Pose.getRotation();
            double thetaSpeed = m_pathThetaController.calculate(
                curRotation.getRadians(), desRotation.getRadians());
            setControl(swreq_drive.withRotationalRate(thetaSpeed));
        }).andThen(Commands.waitUntil(() -> isNearRotation(getState().Pose.getRotation(), desRotation, tolerance)))
          .andThen(() -> setControl(swreq_drive.withRotationalRate(0)));
    }

    /** Translates to a target (x, y) only (no rotation). Stops within `tolerance` meters. */
    public Command roboToTranslation(Translation2d desTranslation, double tolerance) {
        return Commands.runOnce(() -> {
            Translation2d curTranslation = getState().Pose.getTranslation();
            double xSpeed = m_pathXController.calculate(curTranslation.getX(), desTranslation.getX());
            double ySpeed = m_pathYController.calculate(curTranslation.getY(), desTranslation.getY());
            setControl(swreq_drive.withVelocityX(xSpeed).withVelocityY(ySpeed));
        }).andThen(Commands.waitUntil(() -> isNearTranslation(getState().Pose.getTranslation(), desTranslation, tolerance)))
          .andThen(() -> setControl(swreq_drive.withVelocityX(0).withVelocityY(0).withRotationalRate(0)));
    }

    // ---- proximity checks ----

    public boolean isNearPose(Pose2d curPose, Pose2d desPose, double translationTolerance, double rotationTolerance) {
        return isNearTranslation(curPose.getTranslation(), desPose.getTranslation(), translationTolerance)
            && isNearRotation(curPose.getRotation(), desPose.getRotation(), rotationTolerance);
    }

    public boolean isNearPose(Pose2d curPose, Pose2d desPose, double translationTolerance) {
        return isNearTranslation(curPose.getTranslation(), desPose.getTranslation(), translationTolerance);
    }

    public boolean isNearRotation(Rotation2d curRotation, Rotation2d desRotation, double tolerance) {
        // angleModulus wraps the difference into (-π, π] so we always measure the shorter arc.
        return Math.abs(MathUtil.angleModulus(curRotation.getRadians() - desRotation.getRadians())) <= tolerance;
    }

    public boolean isNearTranslation(Translation2d curTranslation, Translation2d desTranslation, double tolerance) {
        return Math.hypot(
            desTranslation.getX() - curTranslation.getX(),
            desTranslation.getY() - curTranslation.getY()
        ) <= tolerance;
    }


    // =============================================================
    // VISION-BASED OBJECT TRACKING
    // =============================================================

    /** Drives to the closest detected object (ball) on the field. */
    public Command swerveToObject() {
        PhotonTrackedTarget target = detection.getClosestObject();
        Pose2d destination = detection.targetToPose(getState().Pose, target);
        detection.addFuel(destination);
        return roboToPose(destination, 0.1);
    }

    /**
     * Computes the robot pose needed to face a fuel location with the intake.
     * Moves the robot to the ball's (x, y) and rotates it so the intake side
     * faces the ball — hence the +180° offset on the approach angle.
     */
    public static Pose2d faceFuelPose(Pose2d robotPose, Pose2d fuelLocation) {
        double dx = fuelLocation.getX() - robotPose.getX();
        double dy = fuelLocation.getY() - robotPose.getY();
        Rotation2d desiredRotation = new Rotation2d(Math.atan2(dy, dx)).plus(Rotation2d.fromDegrees(180));
        return new Pose2d(fuelLocation.getX(), fuelLocation.getY(), desiredRotation);
    }


    // =============================================================
    // PERIODIC
    // =============================================================

    @Override
    public void periodic() {
        // Apply the alliance perspective so field-centric drive works correctly.
        // We re-check every loop while disabled (in case the DS assigns an alliance
        // late) but stop checking once enabled so perspective doesn't flip mid-match.
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            WaltDriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        var state = getState();
        var speeds = m_kinematics.toChassisSpeeds(state.ModuleStates);
        log_vxMPS.accept(speeds.vxMetersPerSecond);
        log_vyMPS.accept(speeds.vyMetersPerSecond);
        log_absoluteRobotSpeed.accept(Math.hypot(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond));
    }


    // =============================================================
    // SIMULATION
    // =============================================================

    // Runs the CTRE drivetrain simulation at 4 ms intervals on a background thread.
    // The faster rate is necessary for the simulated PID loops to behave like real hardware.
    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }
}
